apiVersion: apps/v1
kind: Deployment
metadata:
  name: department
spec:
  selector:
    matchLabels:
      app: department
      version: v1
      type: backend
  template:
    metadata:
      labels:
        app: department
        version: v1
        type: backend
    spec:
      containers:
      - name: department
        image: containersoga/department
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-password        
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb
              key: database-name
---
apiVersion: v1
kind: Service
metadata:
  name: department
spec:
  selector:
    app: department
  ports:
  - port: 8083
    targetPort: 8080
    protocol: TCP
    name: http
