apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
spec:
  selector:
    matchLabels:
      app: employee
      version: v1
      type: backend
  template:
    metadata:
      labels:
        app: employee
        version: v1
        type: backend
    spec:
      containers:
      - name: employee
        image: containersoga/employee
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-password        
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb
              key: database-name
---
apiVersion: v1
kind: Service
metadata:
  name: employee
spec:
  selector:
    app: employee
  ports:
  - port: 8082
    targetPort: 8080
    protocol: TCP
    name: http
